# Copyright (C) 2014 Parker Michaels
# 
# Permission is hereby granted, free of charge, to any person obtaining a 
# copy of this software and associated documentation files (the "Software"), 
# to deal in the Software without restriction, including without limitation 
# the rights to use, copy, modify, merge, publish, distribute, sublicense, 
# and/or sell copies of the Software, and to permit persons to whom the 
# Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
# DEALINGS IN THE SOFTWARE.

import os.path
import platform
from cx_Freeze import setup,Executable

includefiles = [
    os.path.join('Plugins', 'Plugins.json'),
    os.path.join('Plugins', 'FreeBasic', 'FreeBasic.py'),
    os.path.join('Plugins', 'FreeBasic', 'StateMachine.py'),
    os.path.join('Plugins', 'FreeBasic', 'VariableFormatter.py'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'LexicalAnalyzer.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'LexicalAnalyzer.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'ModeStack.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'ModeStack.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'UnicodeNames.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'Windows', 'MemoryMapWindows.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'Windows', 'MemoryMapWindows.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'Linux', 'MemoryMapLinux.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'Linux', 'MemoryMapLinux.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'MemoryMap.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'MemoryMap.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'Unicode.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'Unicode.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'UnicodeConstants.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'UnicodeConstants.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'UnicodeTextStream.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'UnicodeTextStream.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'UTF8Stream.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'UTF8Stream.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'UTF16Stream.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'UTF16Stream.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'UTF32Stream.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'UTF32Stream.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'ASCIIStream.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'ASCIIStream.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'CharacterStream.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'CharacterStream.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'CharacterStreamFromFile.bas'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Stream', 'CharacterStreamFromFile.bi'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Demo', 'make_demo.bat'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Demo', 'make_demo.sh'),
    os.path.join('Plugins', 'FreeBasic', 'Template', 'Demo', 'Demo.bas'),
    os.path.join('Plugins', 'CPlusPlus', 'CPlusPlus.py'),
    os.path.join('Plugins', 'CPlusPlus', 'StateMachine.py'),
    os.path.join('Plugins', 'CPlusPlus', 'VariableFormatter.py'),
    os.path.join('Plugins', 'CPlusPlus', 'Template', 'lexical_analyzer.cpp'),
    os.path.join('Plugins', 'CPlusPlus', 'Template', 'lexical_analyzer.h'),
    os.path.join('Plugins', 'CPlusPlus', 'Template', 'demo', 'demo.cpp'),
    os.path.join('Plugins', 'CPlusPlus', 'Template', 'demo', 'make_demo.sh'),
    os.path.join('Plugins', 'CPlusPlus', 'Template', 'demo', 'make_demo.bat'),
    os.path.join('Plugins', 'Xml', 'Xml.py'),
    os.path.join('Plugins', 'Xml', 'ElementTreeFactory.py'),
    os.path.join('Plugins', 'Xml', 'Template', 'LexicalAnalyzer.xml'),
    os.path.join('Plugins', 'Dot', 'Dot.py'),
    os.path.join('Plugins', 'Dot', 'Template', 'LexicalAnalyzer.dot'),
    os.path.join('Example', 'CLexer', 'CLexer.rules'),
    os.path.join('Example', 'CLexer', 'HelloWorld.c'),
    os.path.join('Example', 'SimpleLexer', 'SimpleLexer.rules'),
    os.path.join('Example', 'SimpleLexer', 'SimpleLexerText.txt'),
    os.path.join('Example', 'FBCLexer', 'FreeBasicLexer.rules'),
    os.path.join('Example', 'FBCLexer', 'HelloWorld.bas'),
    os.path.join('UnicodeData', 'AliasesProperties.json'),
    os.path.join('UnicodeData', 'AliasesProperties.json'),
    os.path.join('UnicodeData', 'AliasesValues.json'),
    os.path.join('UnicodeData', 'BinaryProperties.json'),
    os.path.join('UnicodeData', 'Propertyage.json'),
    os.path.join('UnicodeData', 'Propertyahex.json'),
    os.path.join('UnicodeData', 'Propertyalpha.json'),
    os.path.join('UnicodeData', 'Propertybc.json'),
    os.path.join('UnicodeData', 'Propertybidic.json'),
    os.path.join('UnicodeData', 'Propertybidim.json'),
    os.path.join('UnicodeData', 'Propertyblk.json'),
    os.path.join('UnicodeData', 'Propertybmg.json'),
    os.path.join('UnicodeData', 'Propertybpb.json'),
    os.path.join('UnicodeData', 'Propertybpt.json'),
    os.path.join('UnicodeData', 'Propertycased.json'),
    os.path.join('UnicodeData', 'Propertyccc.json'),
    os.path.join('UnicodeData', 'Propertyce.json'),
    os.path.join('UnicodeData', 'Propertycf.json'),
    os.path.join('UnicodeData', 'Propertyci.json'),
    os.path.join('UnicodeData', 'Propertycompex.json'),
    os.path.join('UnicodeData', 'Propertycwcf.json'),
    os.path.join('UnicodeData', 'Propertycwcm.json'),
    os.path.join('UnicodeData', 'Propertycwkcf.json'),
    os.path.join('UnicodeData', 'Propertycwl.json'),
    os.path.join('UnicodeData', 'Propertycwt.json'),
    os.path.join('UnicodeData', 'Propertycwu.json'),
    os.path.join('UnicodeData', 'Propertydash.json'),
    os.path.join('UnicodeData', 'Propertydep.json'),
    os.path.join('UnicodeData', 'Propertydi.json'),
    os.path.join('UnicodeData', 'Propertydia.json'),
    os.path.join('UnicodeData', 'Propertydm.json'),
    os.path.join('UnicodeData', 'Propertydt.json'),
    os.path.join('UnicodeData', 'Propertyea.json'),
    os.path.join('UnicodeData', 'Propertyext.json'),
    os.path.join('UnicodeData', 'Propertyfcnfkc.json'),
    os.path.join('UnicodeData', 'PropertyFC_NFKC.json'),
    os.path.join('UnicodeData', 'Propertyfirst-cp.json'),
    os.path.join('UnicodeData', 'Propertyfirstcp.json'),
    os.path.join('UnicodeData', 'Propertygc.json'),
    os.path.join('UnicodeData', 'PropertyGCB.json'),
    os.path.join('UnicodeData', 'Propertygrbase.json'),
    os.path.join('UnicodeData', 'Propertygrext.json'),
    os.path.join('UnicodeData', 'Propertygrlink.json'),
    os.path.join('UnicodeData', 'Propertyhex.json'),
    os.path.join('UnicodeData', 'Propertyhst.json'),
    os.path.join('UnicodeData', 'Propertyhyphen.json'),
    os.path.join('UnicodeData', 'Propertyidc.json'),
    os.path.join('UnicodeData', 'Propertyideo.json'),
    os.path.join('UnicodeData', 'Propertyids.json'),
    os.path.join('UnicodeData', 'Propertyidsb.json'),
    os.path.join('UnicodeData', 'Propertyidst.json'),
    os.path.join('UnicodeData', 'PropertyInMC.json'),
    os.path.join('UnicodeData', 'PropertyInSC.json'),
    os.path.join('UnicodeData', 'Propertyisc.json'),
    os.path.join('UnicodeData', 'Propertyjg.json'),
    os.path.join('UnicodeData', 'Propertyjoinc.json'),
    os.path.join('UnicodeData', 'PropertyJSN.json'),
    os.path.join('UnicodeData', 'Propertyjt.json'),
    os.path.join('UnicodeData', 'PropertykAccountingNumeric.json'),
    os.path.join('UnicodeData', 'PropertykBigFive.json'),
    os.path.join('UnicodeData', 'PropertykCangjie.json'),
    os.path.join('UnicodeData', 'PropertykCantonese.json'),
    os.path.join('UnicodeData', 'PropertykCCCII.json'),
    os.path.join('UnicodeData', 'PropertykCheungBauer.json'),
    os.path.join('UnicodeData', 'PropertykCheungBauerIndex.json'),
    os.path.join('UnicodeData', 'PropertykCihaiT.json'),
    os.path.join('UnicodeData', 'PropertykCNS1986.json'),
    os.path.join('UnicodeData', 'PropertykCNS1992.json'),
    os.path.join('UnicodeData', 'PropertykCompatibilityVariant.json'),
    os.path.join('UnicodeData', 'PropertykCowles.json'),
    os.path.join('UnicodeData', 'PropertykDaeJaweon.json'),
    os.path.join('UnicodeData', 'PropertykDefinition.json'),
    os.path.join('UnicodeData', 'PropertykEACC.json'),
    os.path.join('UnicodeData', 'PropertykFenn.json'),
    os.path.join('UnicodeData', 'PropertykFennIndex.json'),
    os.path.join('UnicodeData', 'PropertykFourCornerCode.json'),
    os.path.join('UnicodeData', 'PropertykFrequency.json'),
    os.path.join('UnicodeData', 'PropertykGB0.json'),
    os.path.join('UnicodeData', 'PropertykGB1.json'),
    os.path.join('UnicodeData', 'PropertykGB3.json'),
    os.path.join('UnicodeData', 'PropertykGB5.json'),
    os.path.join('UnicodeData', 'PropertykGB7.json'),
    os.path.join('UnicodeData', 'PropertykGB8.json'),
    os.path.join('UnicodeData', 'PropertykGradeLevel.json'),
    os.path.join('UnicodeData', 'PropertykGSR.json'),
    os.path.join('UnicodeData', 'PropertykHangul.json'),
    os.path.join('UnicodeData', 'PropertykHanYu.json'),
    os.path.join('UnicodeData', 'PropertykHanyuPinlu.json'),
    os.path.join('UnicodeData', 'PropertykHanyuPinyin.json'),
    os.path.join('UnicodeData', 'PropertykHDZRadBreak.json'),
    os.path.join('UnicodeData', 'PropertykHKGlyph.json'),
    os.path.join('UnicodeData', 'PropertykHKSCS.json'),
    os.path.join('UnicodeData', 'PropertykIBMJapan.json'),
    os.path.join('UnicodeData', 'PropertykIICore.json'),
    os.path.join('UnicodeData', 'PropertykIRGDaeJaweon.json'),
    os.path.join('UnicodeData', 'PropertykIRGDaiKanwaZiten.json'),
    os.path.join('UnicodeData', 'Propertykirggsource.json'),
    os.path.join('UnicodeData', 'PropertykIRGHanyuDaZidian.json'),
    os.path.join('UnicodeData', 'Propertykirghsource.json'),
    os.path.join('UnicodeData', 'Propertykirgjsource.json'),
    os.path.join('UnicodeData', 'PropertykIRGKangXi.json'),
    os.path.join('UnicodeData', 'Propertykirgkpsource.json'),
    os.path.join('UnicodeData', 'Propertykirgksource.json'),
    os.path.join('UnicodeData', 'Propertykirgmsource.json'),
    os.path.join('UnicodeData', 'Propertykirgtsource.json'),
    os.path.join('UnicodeData', 'Propertykirgusource.json'),
    os.path.join('UnicodeData', 'Propertykirgvsource.json'),
    os.path.join('UnicodeData', 'PropertykIRG_GSource.json'),
    os.path.join('UnicodeData', 'PropertykIRG_HSource.json'),
    os.path.join('UnicodeData', 'PropertykIRG_JSource.json'),
    os.path.join('UnicodeData', 'PropertykIRG_KPSource.json'),
    os.path.join('UnicodeData', 'PropertykIRG_KSource.json'),
    os.path.join('UnicodeData', 'PropertykIRG_MSource.json'),
    os.path.join('UnicodeData', 'PropertykIRG_TSource.json'),
    os.path.join('UnicodeData', 'PropertykIRG_USource.json'),
    os.path.join('UnicodeData', 'PropertykIRG_VSource.json'),
    os.path.join('UnicodeData', 'PropertykJapaneseKun.json'),
    os.path.join('UnicodeData', 'PropertykJapaneseOn.json'),
    os.path.join('UnicodeData', 'PropertykJis0.json'),
    os.path.join('UnicodeData', 'PropertykJIS0213.json'),
    os.path.join('UnicodeData', 'PropertykJis1.json'),
    os.path.join('UnicodeData', 'PropertykKangXi.json'),
    os.path.join('UnicodeData', 'PropertykKarlgren.json'),
    os.path.join('UnicodeData', 'PropertykKorean.json'),
    os.path.join('UnicodeData', 'PropertykKPS0.json'),
    os.path.join('UnicodeData', 'PropertykKPS1.json'),
    os.path.join('UnicodeData', 'PropertykKSC0.json'),
    os.path.join('UnicodeData', 'PropertykKSC1.json'),
    os.path.join('UnicodeData', 'PropertykLau.json'),
    os.path.join('UnicodeData', 'PropertykMainlandTelegraph.json'),
    os.path.join('UnicodeData', 'PropertykMandarin.json'),
    os.path.join('UnicodeData', 'PropertykMatthews.json'),
    os.path.join('UnicodeData', 'PropertykMeyerWempe.json'),
    os.path.join('UnicodeData', 'PropertykMorohashi.json'),
    os.path.join('UnicodeData', 'PropertykNelson.json'),
    os.path.join('UnicodeData', 'PropertykOtherNumeric.json'),
    os.path.join('UnicodeData', 'PropertykPhonetic.json'),
    os.path.join('UnicodeData', 'PropertykPrimaryNumeric.json'),
    os.path.join('UnicodeData', 'PropertykPseudoGB1.json'),
    os.path.join('UnicodeData', 'Propertykrsadobejapan16.json'),
    os.path.join('UnicodeData', 'PropertykRSAdobe_Japan1_6.json'),
    os.path.join('UnicodeData', 'PropertykRSJapanese.json'),
    os.path.join('UnicodeData', 'PropertykRSKangXi.json'),
    os.path.join('UnicodeData', 'PropertykRSKanWa.json'),
    os.path.join('UnicodeData', 'PropertykRSKorean.json'),
    os.path.join('UnicodeData', 'PropertykRSUnicode.json'),
    os.path.join('UnicodeData', 'PropertykSBGY.json'),
    os.path.join('UnicodeData', 'PropertykSemanticVariant.json'),
    os.path.join('UnicodeData', 'PropertykSimplifiedVariant.json'),
    os.path.join('UnicodeData', 'PropertykSpecializedSemanticVariant.json'),
    os.path.join('UnicodeData', 'PropertykTaiwanTelegraph.json'),
    os.path.join('UnicodeData', 'PropertykTang.json'),
    os.path.join('UnicodeData', 'PropertykTotalStrokes.json'),
    os.path.join('UnicodeData', 'PropertykTraditionalVariant.json'),
    os.path.join('UnicodeData', 'PropertykVietnamese.json'),
    os.path.join('UnicodeData', 'PropertykXerox.json'),
    os.path.join('UnicodeData', 'PropertykXHC1983.json'),
    os.path.join('UnicodeData', 'PropertykZVariant.json'),
    os.path.join('UnicodeData', 'Propertylast-cp.json'),
    os.path.join('UnicodeData', 'Propertylastcp.json'),
    os.path.join('UnicodeData', 'Propertylb.json'),
    os.path.join('UnicodeData', 'Propertylc.json'),
    os.path.join('UnicodeData', 'Propertyloe.json'),
    os.path.join('UnicodeData', 'Propertylower.json'),
    os.path.join('UnicodeData', 'Propertymath.json'),
    os.path.join('UnicodeData', 'Propertyna.json'),
    os.path.join('UnicodeData', 'Propertyna1.json'),
    os.path.join('UnicodeData', 'Propertynchar.json'),
    os.path.join('UnicodeData', 'Propertynfcqc.json'),
    os.path.join('UnicodeData', 'PropertyNFC_QC.json'),
    os.path.join('UnicodeData', 'Propertynfdqc.json'),
    os.path.join('UnicodeData', 'Propertynfkccf.json'),
    os.path.join('UnicodeData', 'Propertynfkcqc.json'),
    os.path.join('UnicodeData', 'PropertyNFKC_CF.json'),
    os.path.join('UnicodeData', 'PropertyNFKC_QC.json'),
    os.path.join('UnicodeData', 'Propertynfkdqc.json'),
    os.path.join('UnicodeData', 'Propertynt.json'),
    os.path.join('UnicodeData', 'Propertynv.json'),
    os.path.join('UnicodeData', 'Propertyoalpha.json'),
    os.path.join('UnicodeData', 'Propertyodi.json'),
    os.path.join('UnicodeData', 'Propertyogrext.json'),
    os.path.join('UnicodeData', 'Propertyoidc.json'),
    os.path.join('UnicodeData', 'Propertyoids.json'),
    os.path.join('UnicodeData', 'Propertyolower.json'),
    os.path.join('UnicodeData', 'Propertyomath.json'),
    os.path.join('UnicodeData', 'Propertyoupper.json'),
    os.path.join('UnicodeData', 'Propertypatsyn.json'),
    os.path.join('UnicodeData', 'Propertypatws.json'),
    os.path.join('UnicodeData', 'Propertyqmark.json'),
    os.path.join('UnicodeData', 'Propertyradical.json'),
    os.path.join('UnicodeData', 'PropertySB.json'),
    os.path.join('UnicodeData', 'Propertysc.json'),
    os.path.join('UnicodeData', 'Propertyscf.json'),
    os.path.join('UnicodeData', 'Propertyscx.json'),
    os.path.join('UnicodeData', 'Propertysd.json'),
    os.path.join('UnicodeData', 'Propertyslc.json'),
    os.path.join('UnicodeData', 'Propertystc.json'),
    os.path.join('UnicodeData', 'Propertysterm.json'),
    os.path.join('UnicodeData', 'Propertysuc.json'),
    os.path.join('UnicodeData', 'Propertytc.json'),
    os.path.join('UnicodeData', 'Propertyterm.json'),
    os.path.join('UnicodeData', 'Propertyuc.json'),
    os.path.join('UnicodeData', 'Propertyuideo.json'),
    os.path.join('UnicodeData', 'Propertyupper.json'),
    os.path.join('UnicodeData', 'Propertyvs.json'),
    os.path.join('UnicodeData', 'PropertyWB.json'),
    os.path.join('UnicodeData', 'Propertywspace.json'),
    os.path.join('UnicodeData', 'Propertyxidc.json'),
    os.path.join('UnicodeData', 'Propertyxids.json'),
    os.path.join('UnicodeData', 'Propertyxonfc.json'),
    os.path.join('UnicodeData', 'Propertyxonfd.json'),
    os.path.join('UnicodeData', 'Propertyxonfkc.json'),
    os.path.join('UnicodeData', 'Propertyxonfkd.json'),
    'README',
    'LICENSE',
    'CHANGELIST'
]
includes = [
    'Generator.Emitter.CachedFormatter',
    'Generator.Emitter.EmitCode',
    'Generator.Emitter.FileTemplate',
    'Generator.Emitter.PluginTemplate'
]
excludes = []
packages = ['blist']
target_name = "Poodle-Lex"
if platform.system() == "Windows":
    target_name += ".exe"
setup(
    name = 'Poodle-Lex',
    version = '1.9.7',
    description = 'A lexical analyzer generator with support for multiple languages.',
    author = 'Parker Michaels',
    author_email = 'parkertomatoes@gmail.com',
    options = {
        'build_exe': {
            'excludes':excludes,
            'includes':includes,
            'packages':packages,
            'include_files':includefiles
        },
        'bdist_msi': {
            'upgrade_code': '{d7bbdad8-411a-4662-bc31-f5494b9cd11f}'
        }
    }, 
    executables = [Executable('__main__.py', targetName=target_name)]
)
